import "@/app/global.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import NavBar from "@/components/NavBar/NavBar";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">  
    <head>
        <link rel="icon" href="/favicon.png" />
      </head>   
      <body>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
